export const leaveTypeForm = {
    component: "form",
    mode: "editMode",
    title: "Leave Type Details",
    classname: "grid-cols-12",
    fields: [
      {
        type: "text",
        tag: "input",
        label: "Name",
        name: "name",
        required: true,
        icon: "",
        classname:"col-span-2",
        editable: true,
      },
      {
        type: "text",
        tag: "input",
        label: "Code",
        name: "code",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
      },
      {
        type: "select",
        tag: "select",
        label: "Type",
        name: "type",
        classname:"col-span-2",
        required: true,
        icon: "",
        editable: true,
        options: [
          { label: "Casual Leave", value: "casual" },
          { label: "Sick Leave", value: "sick" },
          { label: "Earned Leave", value: "earned" },
        ],
      },
      {
        type: "radio",
        tag: "input",
        label: "Leave Unit",
        name: "leave_unit",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        options: [
          { label: "Days", value: "days" },
          { label: "Hours", value: "hours" },
        ],
      },
      {
        type: "textarea",
        tag: "textarea",
        label: "Description",
        name: "description",
        classname:"col-span-2",
        required: true,
        icon: "",
        editable: true,
      },
      {
        type: "select",
        tag: "select",
        label: "For Role",
        name: "for_role",
        classname:"col-span-2",
        required: true,
        icon: "",
        editable: true,
        options: [
          { label: "Please select...", value: "" },
          { label: "Manager", value: "manager" },
          { label: "Employee", value: "employee" },
          { label: "HR", value: "hr" },
        ],
      },
      {
        type: "radio",
        tag: "input",
        label: "Gender",
        name: "gender",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        options: [
          { label: "All", value: "all" },
          { label: "Male", value: "male" },
          { label: "Female", value: "female" },
        ],
      },
      {
        type: "radio",
        tag: "input",
        label: "Marital Status",
        name: "marital_status",
        required: true,
        icon: "",
        classname:"col-span-2",
        editable: true,
        options: [
          { label: "All", value: "all" },
          { label: "Married", value: "married" },
          { label: "Un-Married", value: "unmarried" },
        ],
      },
      {
        type: "radio",
        tag: "input",
        label: "For",
        name: "for_type",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        options: [
          { label: "All", value: "all" },
          { label: "Experienced based", value: "experienced" },
        ],
      },
      {
        type: "select",
        tag: "select",
        label: "Period",
        name: "period",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        options: [
          { label: "Select Type", value: "" },
          { label: "Monthly", value: "monthly" },
          { label: "Yearly", value: "yearly" },
        ],
      },
      {
        type: "number",
        tag: "input",
        label: "Leave Count",
        name: "leave_count",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        defaultValue: "1",
      },
      {
        type: "number",
        tag: "input",
        label: "For New Joinee",
        name: "for_new_joinee",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        defaultValue: "1",
      },
      {
        type: "number",
        tag: "input",
        label: "After six months",
        name: "after_six_months",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        defaultValue: "1",
      },
      {
        type: "select",
        tag: "select",
        label: "Leave Credit on Every",
        name: "leave_credit_on_every",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        options: [
          { label: "Select Type", value: "" },
          { label: "Month Start", value: "month_start" },
          { label: "Month End", value: "month_end" },
          { label: "Year Start", value: "year_start" },
          { label: "Year End", value: "year_end" },
        ],
      },
      {
        type: "number",
        tag: "input",
        label: "Leave Credit",
        name: "leave_credit",
        required: true,
        classname:"col-span-2",
        icon: "",
        editable: true,
        defaultValue: "1.00",
      },
    ],
    actions: [
      {
        type: "button",
        label: "Save",
        action: "save",
        variant: "primary",
      },
      {
        type: "button",
        label: "Cancel",
        action: "cancel",
        variant: "secondary",
      },
    ],
  }
  
  export const leaveTypes = [
    {
      name: "Casual Leave",
      code: "CL",
      type: "casual",
      leave_unit: "days",
      description: "Leave for personal work and emergencies",
      for_role: "employee",
      gender: "all",
      marital_status: "all",
      for_type: "all",
      period: "yearly",
      leave_count: 12,
      for_new_joinee: 1,
      after_six_months: 6,
      leave_credit_on_every: "year_start",
      leave_credit: 1.0,
    },
    {
      name: "Sick Leave",
      code: "SL",
      type: "sick",
      leave_unit: "days",
      description: "Leave for medical reasons",
      for_role: "employee",
      gender: "all",
      marital_status: "all",
      for_type: "all",
      period: "yearly",
      leave_count: 12,
      for_new_joinee: 1,
      after_six_months: 6,
      leave_credit_on_every: "month_start",
      leave_credit: 1.0,
    },
  ]
  
  