export const visitorForm = {
    component: "form",
    mode: "editMode",
    title: "Visitor Management Form",
    class: "grid-cols-2",
    fields: [
      {
        type: "tel",
        tag: "input",
        label: "MobileNumber",
        name: "mobile_number",
        required: true,
        icon: "",
        editable: true,
      },
      {
        type: "date",
        tag: "input",
        label: "Date",
        name: "date",
        required: true,
        icon: "",
        editable: true,
      },
      {
        type: "text",
        tag: "input",
        label: "VisitorId",
        name: "visitor_id",
        required: true,
        icon: "",
        editable: false,
      },
      {
        type: "select",
        tag: "select",
        label: "BadgeNumber",
        name: "badge_number",
        required: true,
        icon: "",
        editable: true,
        options: [
          { label: "B001", value: "B001" },
          { label: "B002", value: "B002" },
          { label: "B003", value: "B003" },
        ],
      },
      {
        type: "text",
        tag: "input",
        label: "VisitorName",
        name: "visitor_name",
        required: true,
        icon: "",
        editable: true,
      },
      {
        type: "text",
        tag: "input",
        label: "Company",
        name: "company",
        required: true,
        icon: "",
        editable: true,
      },
      {
        type: "number",
        tag: "input",
        label: "NoOfPersons",
        name: "no_of_persons",
        required: true,
        icon: "",
        editable: true,
      },
      {
        type: "select",
        tag: "select",
        label: "Nationality",
        name: "nationality",
        required: true,
        icon: "",
        editable: true,
        options: [
          { label: "Indian", value: "Indian" },
          { label: "American", value: "American" },
          { label: "British", value: "British" },
        ],
      },
      {
        type: "select",
        tag: "select",
        label: "Purpose",
        name: "purpose",
        required: true,
        icon: "",
        editable: true,
        options: [
          { label: "Meeting", value: "Meeting" },
          { label: "Interview", value: "Interview" },
          { label: "Delivery", value: "Delivery" },
        ],
      },
      {
        type: "select",
        tag: "select",
        label: "IdProof",
        name: "id_proof",
        required: true,
        icon: "",
        editable: true,
        options: [
          { label: "Passport", value: "Passport" },
          { label: "Driving License", value: "Driving License" },
          { label: "National ID", value: "National ID" },
        ],
      },
      {
        type: "text",
        tag: "input",
        label: "IdProofNumber",
        name: "id_proof_number",
        required: true,
        icon: "",
        editable: true,
      },
      {
        type: "select",
        tag: "select",
        label: "LaptopToBePermitted",
        name: "laptop_to_be_permitted",
        required: true,
        icon: "",
        editable: true,
        options: [
          { label: "Yes", value: "Yes" },
          { label: "No", value: "No" },
        ],
      },
      {
        type: "text",
        tag: "input",
        label: "OtherMediaItems",
        name: "other_media_items",
        required: false,
        icon: "",
        editable: true,
      },
      {
        type: "select",
        tag: "select",
        label: "VisitingEmployee",
        name: "visiting_employee",
        required: true,
        icon: "",
        editable: true,
        options: [
          { label: "John Smith", value: "John Smith" },
          { label: "Jane Doe", value: "Jane Doe" },
        ],
      },
      {
        type: "text",
        tag: "input",
        label: "VisitingDepartment",
        name: "visiting_department",
        required: true,
        icon: "",
        editable: true,
      },
      {
        type: "textarea",
        tag: "textarea",
        label: "Remarks",
        name: "remarks",
        required: false,
        icon: "",
        editable: true,
      },
      {
        type: "textarea",
        tag: "textarea",
        label: "Address",
        name: "address",
        required: true,
        icon: "",
        editable: true,
      },
    ],
    actions: [
        {
            type: "button",
            label: "Submit",
            action: "save",
            icon: "save",
          },
      {
        type: "button",
        label: "Cancel",
        action: "cancel",
      },
    ],
  }